export const GET_MAP = "GET_MAP";
export const REMOVE_LAYER = "REMOVE_LAYER";
export const ADD_LAYER = "ADD_LAYER";
export const SET_USER = "SET_USER";
export const UPDATE_POSITION = "UPDATE_POSITION";
export const SET_ORIGIN_DESTINATION_POSITION =
  "SET_ORIGIN_DESTINATION_POSITION";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const CHANGE_VIEW = "CHANGE_VIEW";
export const RESIZE_MAP = "RESIZE_MAP";
